export const mockLeaveRequests = [
  {
    id: 1,
    employee: "أحمد حسن محمد",
    type: "إجازة سنوية",
    startDate: "2024-06-15",
    endDate: "2024-06-20",
    days: 5,
    status: "pending",
    reason: "قضاء عطلة عائلية",
    department: "تكنولوجيا المعلومات",
    avatar: "AH",
    avatarBg: "bg-blue-100",
    avatarColor: "text-blue-700",
    aiRecommendation: "approve",
    aiReason: "رصيد الموظف كافي ولا يوجد تعارض في الفريق",
  },
  {
    id: 2,
    employee: "سارة أحمد علي",
    type: "إجازة مرضية",
    startDate: "2024-06-14",
    endDate: "2024-06-16",
    days: 3,
    status: "approved",
    reason: "إجازة مرضية طارئة",
    department: "الموارد البشرية",
    avatar: "SA",
    avatarBg: "bg-purple-100",
    avatarColor: "text-purple-700",
    aiRecommendation: "approve",
    aiReason: "إجازة مرضية مع شهادة طبية",
  },
  {
    id: 3,
    employee: "محمد كريم عبدالله",
    type: "إجازة خاصة",
    startDate: "2024-06-18",
    endDate: "2024-06-19",
    days: 2,
    status: "pending",
    reason: "شؤون عائلية",
    department: "المبيعات",
    avatar: "MK",
    avatarBg: "bg-green-100",
    avatarColor: "text-green-700",
    aiRecommendation: "review",
    aiReason: "3 موظفين بالفعل في إجازة من نفس القسم",
  },
  {
    id: 4,
    employee: "فاطمة نور الدين",
    type: "إجازة سنوية",
    startDate: "2024-06-10",
    endDate: "2024-06-25",
    days: 15,
    status: "approved",
    reason: "سفر للخارج",
    department: "المالية",
    avatar: "FN",
    avatarBg: "bg-amber-100",
    avatarColor: "text-amber-700",
    aiRecommendation: "approve",
    aiReason: "رصيد كافي وتم التخطيط مسبقاً",
  },
  {
    id: 5,
    employee: "عمر فاروق",
    type: "إجازة بدون راتب",
    startDate: "2024-06-20",
    endDate: "2024-07-01",
    days: 10,
    status: "rejected",
    reason: "سفر شخصي",
    department: "تكنولوجيا المعلومات",
    avatar: "OF",
    avatarBg: "bg-red-100",
    avatarColor: "text-red-700",
    aiRecommendation: "review",
    aiReason: "فترة طويلة قد تؤثر على المشاريع الحالية",
  },
];

export const mockRewardRequests = [
  {
    id: 101,
    employee: "Salma yasser",
    department: "Sales",
    fromDate: "2026-05-24",
    amount: 3000,
    currency: "EGP",
    status: "pending",
    reason: "أداء متميز في إغلاق صفقات الربع الثاني",
    avatar: "SY",
    avatarBg: "bg-pink-100",
    avatarColor: "text-pink-700",
  },
  {
    id: 102,
    employee: "Salma yasser",
    department: "Sales",
    fromDate: "2026-05-24",
    amount: 3000,
    currency: "EGP",
    status: "pending",
    reason: "تجاوز هدف المبيعات الشهري",
    avatar: "SY",
    avatarBg: "bg-pink-100",
    avatarColor: "text-pink-700",
  },
];

export const mockPermissionRequests = [
  {
    id: 201,
    employee: "abdelrahman ali",
    department: "front-end",
    date: "2026-05-24",
    hours: 3,
    status: "pending",
    reason: "موعد طبي",
    avatar: "AA",
    avatarBg: "bg-amber-100",
    avatarColor: "text-amber-700",
  },
  {
    id: 202,
    employee: "abdelrahman ali",
    department: "front-end",
    date: "2026-05-24",
    hours: 3,
    status: "pending",
    reason: "ظرف عائلي طارئ",
    avatar: "AA",
    avatarBg: "bg-amber-100",
    avatarColor: "text-amber-700",
  },
  {
    id: 203,
    employee: "abdelrahman ali",
    department: "front-end",
    date: "2026-05-24",
    hours: 3,
    status: "pending",
    reason: "إجراء إداري",
    avatar: "AA",
    avatarBg: "bg-amber-100",
    avatarColor: "text-amber-700",
  },
];

export const mockSalaryIncreaseRequests = [
  {
    id: 301,
    employee: "كريم محمود",
    department: "تكنولوجيا المعلومات",
    fromDate: "2026-05-20",
    currentSalary: 12000,
    requestedSalary: 14000,
    currency: "EGP",
    status: "pending",
    reason: "زيادة المسؤوليات والخبرة المكتسبة خلال السنة الأخيرة",
    avatar: "KM",
    avatarBg: "bg-indigo-100",
    avatarColor: "text-indigo-700",
  },
  {
    id: 302,
    employee: "نورهان سامي",
    department: "المالية",
    fromDate: "2026-05-22",
    currentSalary: 9000,
    requestedSalary: 10500,
    currency: "EGP",
    status: "pending",
    reason: "مواءمة الراتب مع متوسط السوق",
    avatar: "NS",
    avatarBg: "bg-indigo-100",
    avatarColor: "text-indigo-700",
  },
];

export const mockRemoteWorkRequests = [
  {
    id: 401,
    employee: "ياسمين عادل",
    department: "تكنولوجيا المعلومات",
    fromDate: "2026-06-01",
    toDate: "2026-06-05",
    days: 5,
    status: "pending",
    reason: "ظروف عائلية تتطلب التواجد المنزلي",
    avatar: "YA",
    avatarBg: "bg-teal-100",
    avatarColor: "text-teal-700",
  },
  {
    id: 402,
    employee: "حسام الدين طارق",
    department: "المبيعات",
    fromDate: "2026-06-10",
    toDate: "2026-06-10",
    days: 1,
    status: "pending",
    reason: "إنجاز مهمة تتطلب تركيز دون مقاطعات المكتب",
    avatar: "HT",
    avatarBg: "bg-teal-100",
    avatarColor: "text-teal-700",
  },
];

export const mockAdvanceRequests = [
  {
    id: 501,
    employee: "مريم عصام",
    department: "الموارد البشرية",
    fromDate: "2026-05-28",
    repaymentDate: "2026-08-28",
    amount: 5000,
    currency: "EGP",
    status: "pending",
    reason: "ظرف طبي عاجل لأحد أفراد الأسرة",
    avatar: "MA",
    avatarBg: "bg-rose-100",
    avatarColor: "text-rose-700",
  },
  {
    id: 502,
    employee: "طارق ممدوح",
    department: "تكنولوجيا المعلومات",
    fromDate: "2026-05-30",
    repaymentDate: "2026-08-30",
    amount: 2500,
    currency: "EGP",
    status: "pending",
    reason: "مصاريف دراسية طارئة",
    avatar: "TM",
    avatarBg: "bg-rose-100",
    avatarColor: "text-rose-700",
  },
];

export const mockLeaveColumnRequests = mockLeaveRequests.map((r) => ({
  id: r.id,
  employee: r.employee,
  department: r.department,
  fromDate: r.startDate,
  toDate: r.endDate,
  status: r.status,
  reason: r.reason,
  days: r.days,
  type: r.type,
  avatar: r.avatar,
  avatarBg: r.avatarBg,
  avatarColor: r.avatarColor,
  aiRecommendation: r.aiRecommendation,
  aiReason: r.aiReason,
}));
