export const employees = [
  {
    id: 1,
    name: "أحمد حسن محمد",
    email: "ahmed.hassan@company.com",
    phone: "+20 123 456 7890",
    department: "تكنولوجيا المعلومات",
    position: "مطور واجهات أمامية",
    salary: "EGB 15,000",
    status: "active",
    joinDate: "2023-01-15",
    location: "القاهرة",
    avatar: "AH",
    avatarBg: "bg-blue-100",
    avatarColor: "text-blue-700",
    photo: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 2,
    name: "سارة أحمد علي",
    email: "sara.ali@company.com",
    phone: "+20 987 654 3210",
    department: "الموارد البشرية",
    position: "مدير موارد بشرية",
    salary: "EGB 18,000",
    status: "active",
    joinDate: "2022-06-01",
    location: "القاهرة",
    avatar: "SA",
    avatarBg: "bg-purple-100",
    avatarColor: "text-purple-700",
    photo: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: 3,
    name: "محمد كريم عبدالله",
    email: "mohamed.karim@company.com",
    phone: "+20 555 123 4567",
    department: "المبيعات",
    position: "مدير مبيعات",
    salary: "EGB 20,000",
    status: "active",
    joinDate: "2021-09-10",
    location: "الإسكندرية",
    avatar: "MK",
    avatarBg: "bg-green-100",
    avatarColor: "text-green-700",
    photo: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: 4,
    name: "فاطمة نور الدين",
    email: "fatima.nour@company.com",
    phone: "+20 111 222 3333",
    department: "المالية",
    position: "محاسب",
    salary: "EGB 12,000",
    status: "on-leave",
    joinDate: "2023-03-20",
    location: "القاهرة",
    avatar: "FN",
    avatarBg: "bg-amber-100",
    avatarColor: "text-amber-700",
    photo: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 5,
    name: "عمر فاروق",
    email: "omar.farouk@company.com",
    phone: "+20 444 555 6666",
    department: "تكنولوجيا المعلومات",
    position: "مهندس برمجيات",
    salary: "EGB 16,000",
    status: "active",
    joinDate: "2022-11-05",
    location: "القاهرة",
    avatar: "OF",
    avatarBg: "bg-red-100",
    avatarColor: "text-red-700",
    photo: "https://i.pravatar.cc/150?img=22",
  },
  {
    id: 6,
    name: "ليلى محمود",
    email: "layla.mahmoud@company.com",
    phone: "+20 777 888 9999",
    department: "التسويق",
    position: "مسوق رقمي",
    salary: "EGB 14,000",
    status: "inactive",
    joinDate: "2020-07-15",
    location: "الجيزة",
    avatar: "LM",
    avatarBg: "bg-gray-100",
    avatarColor: "text-gray-700",
    photo: "https://i.pravatar.cc/150?img=38",
  },
];

export const departments = [
  "الكل",
  "تكنولوجيا المعلومات",
  "الموارد البشرية",
  "المبيعات",
  "المالية",
  "التسويق",
];

 

export const employmentTypes = [
  "full_time",
  "part_time",
  "contract",
  "freelance",
];

export const branches = [
  "Cairo Branch",
  "Alexandria Branch",
  "Giza Branch",
];

export const statusFilters = [
  { value: "all", label: "الكل" },
  { value: "active", label: "نشط" },
  { value: "on-leave", label: "في إجازة" },
  { value: "inactive", label: "غير نشط" },
];
 

export const PAGE_SIZE = 40;
